name: Validate Version

on:
  workflow_call:

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
    - name: 🗃️ Checkout
      uses: actions/checkout@v4

    - name: ⛏️ Extract version from csproj
      id: csproj
      shell: pwsh
      env:
        PROJECT_NAME: ${{ github.event.repository.name }}
      run: |
        $version = .github/workflows/scripts/Get-Version.ps1 -FilePath "src/$($env:PROJECT_NAME)"

        Write-Output "Project version: $version"
        Write-Output "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: 🟰 Compare tag with csproj version
      shell: pwsh
      run: |
        $tag = $env:GITHUB_REF_NAME

        $csprojVersion = "${{ steps.csproj.outputs.version }}"

        if ($tag. -ne $csprojVersion) {
            Write-Output "Version mismatch:"
            Write-Output "  Tag:      $tag"
            Write-Output "  csproj:   $csprojVersion"
            exit 1
        }

        